COMMAND_REMOTE_DOORLOCK = "COMMAND_REMOTE_DOORLOCK"
COMMAND_REMOTE_DOORUNLOCK = "COMMAND_REMOTE_DOORUNLOCK"
RESPONSE_REMOTE_DOORLOCK = "RESPONSE_REMOTE_DOORLOCK"
RESPONSE_REMOTE_DOORUNLOCK = "RESPONSE_REMOTE_DOORUNLOCK"